spring:
  application:
    name: gateway-mvc-service

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url-auth}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# Zipkin & Micrometer
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# JWT
jwt:
  auth:
    converter:
      resource-id: ${keycloak.client-id}
      principle-attribute: preferred_username

# Keycloak
keycloak:
  realm: bies_s
  client-id: bies_s_rest_api
  url-auth: http://keycloak:8080

# Server
server:
  port: 8080

# Paths
path:
  users: /api/v1/users/**
  auth: /api/v1/auth/**
  token: /api/v1/token/refresh
  idea: /api/v1/idea/**
  user-service-domain: http://user-service:8080
  idea-service-domain: http://idea-service:8080

# Debug
logging:
  level:
    web: DEBUG
