spring:
  application:
    name: gateway-reactive-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${path.user-service-domain}
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/token/**
          filters:
            - StripPrefix=2

        - id: idea-service
          uri: ${path.idea-service-domain}
          predicates:
            - Path=/api/v1/idea/**
          filters:
            - StripPrefix=2


  # Security
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak.url-auth}/realms/${keycloak.realm}/protocol/openid-connect/certs

# Zipkin & Micrometer
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# JWT
jwt:
  auth:
    converter:
      resource-id: ${keycloak.client-id}

# Keycloak
keycloak:
  realm: bies_s
  client-id: bies_s_rest_api
  url-auth: http://keycloak:8080

# Server
server:
  port: 8080

# Paths
path:
  user-service-domain: http://user-service:8080
  idea-service-domain: http://idea-service:8080

# Debug
logging:
  level:
    web: DEBUG